#!/usr/bin/env python3
"""Generate Levels.swift from NetHack 3.6's dat/sokoban.des.

Coordinates in the .des file are (x, y) = (column, row), 0-based from the
top-left of the MAP block. We keep them as-is.
"""
import re, sys, pathlib

here = pathlib.Path(__file__).parent
src = (here / "sokoban.des").read_text().splitlines()

levels = []
cur = None
in_map = False
for line in src:
    if line.startswith("MAZE:"):
        name = re.match(r'MAZE:"([^"]+)"', line).group(1)
        cur = dict(id=name, rows=[], boulders=[], traps=[], doors=[], scrolls=[],
                   trapKind=None, start=None, exit=None, places=[])
        levels.append(cur)
        continue
    if cur is None:
        continue
    if line == "MAP":
        in_map = True; continue
    if line == "ENDMAP":
        in_map = False; continue
    if in_map:
        cur["rows"].append(line); continue
    m = re.match(r'BRANCH:\((\d+),(\d+),', line)
    if m:
        cur["start"] = (int(m[1]), int(m[2])); continue
    m = re.match(r'STAIR:\((\d+),(\d+)\),(up|down)', line)
    if m:
        p = (int(m[1]), int(m[2]))
        if m[3] == "up": cur["exit"] = p
        else: cur["start"] = p; cur["downstairs"] = p
        continue
    m = re.match(r'DOOR:\w+,\((\d+),(\d+)\)', line)
    if m:
        cur["doors"].append((int(m[1]), int(m[2]))); continue
    m = re.match(r'OBJECT:\(\'`\',"boulder"\),\((\d+),(\d+)\)', line)
    if m:
        cur["boulders"].append((int(m[1]), int(m[2]))); continue
    m = re.match(r'OBJECT:\(\'\?\',"earth"\),\((\d+),(\d+)\)', line)
    if m:
        cur["scrolls"].append((int(m[1]), int(m[2]))); continue
    m = re.match(r'TRAP:"(pit|hole)",\((\d+),(\d+)\)', line)
    if m:
        cur["trapKind"] = m[1]
        cur["traps"].append((int(m[2]), int(m[3]))); continue
    m = re.match(r'\$place = \{(.*)\}', line)
    if m:
        cur["places"] = [(int(a), int(b)) for a, b in re.findall(r'\((\d+),(\d+)\)', m[1])]
        continue

# Validate: every placed thing sits on a floor-ish square, sizes are sane.
def cell(lv, p):
    x, y = p
    row = lv["rows"][y]
    return row[x] if x < len(row) else " "

for lv in levels:
    w = max(len(r) for r in lv["rows"])
    lv["rows"] = [r.ljust(w) for r in lv["rows"]]
    for p in lv["boulders"] + lv["traps"] + lv["places"] + lv["scrolls"] + [lv["start"]] + ([lv["exit"]] if lv["exit"] else []):
        assert cell(lv, p) == ".", (lv["id"], p, cell(lv, p))
    for p in lv["doors"]:
        assert cell(lv, p) == "+", (lv["id"], p, cell(lv, p))
    # Every '+' in the map should be a declared door.
    for y, r in enumerate(lv["rows"]):
        for x, ch in enumerate(r):
            if ch == "+":
                assert (x, y) in lv["doors"], (lv["id"], (x, y))
    assert len(lv["boulders"]) >= len(lv["traps"]), lv["id"]
    assert len(set(lv["boulders"])) == len(lv["boulders"])
    assert not set(lv["scrolls"]) & set(lv["boulders"]), lv["id"]
    print(f'{lv["id"]}: {w}x{len(lv["rows"])} boulders={len(lv["boulders"])} traps={len(lv["traps"])} ({lv["trapKind"]}) start={lv["start"]} exit={lv["exit"]} places={lv["places"]} scrolls={lv["scrolls"]}', file=sys.stderr)

# NetHack numbers the levels from the top: soko1 is the prize level and
# soko4 is where you enter. The app presents them in play order.
order = ["soko4", "soko3", "soko2", "soko1"]
def stage(lv): return order.index(lv["id"].split("-")[0]) + 1
def variant(lv): return "AB"[int(lv["id"].split("-")[1]) - 1]
levels.sort(key=lambda lv: (stage(lv), variant(lv)))

def pt(p): return f"P({p[0]}, {p[1]})"
def pts(ps): return "[" + ", ".join(pt(p) for p in ps) + "]"

out = []
out.append("// Generated by tools/gen_levels.py from NetHack 3.6 dat/sokoban.des.")
out.append("// Level layouts Copyright (c) 1998-1999 by Kevin Hugo; see NOTICE.md.")
out.append("// Do not edit by hand.")
out.append("")
out.append("import Foundation")
out.append("")
out.append("private typealias P = Point")
out.append("")
out.append("enum SokobanLevels {")
out.append("    static let all: [LevelDef] = [")
for lv in levels:
    out.append("        LevelDef(")
    out.append(f'            id: "{lv["id"]}",')
    out.append(f'            stage: {stage(lv)},')
    out.append(f'            variant: "{variant(lv)}",')
    out.append("            rows: [")
    for r in lv["rows"]:
        out.append(f'                "{r}",')
    out.append("            ],")
    out.append(f'            start: {pt(lv["start"])},')
    out.append(f'            exit: {pt(lv["exit"]) if lv["exit"] else "nil"},')
    out.append(f'            trapKind: .{lv["trapKind"]},')
    out.append(f'            boulders: {pts(lv["boulders"])},')
    out.append(f'            traps: {pts(lv["traps"])},')
    out.append(f'            doors: {pts(lv["doors"])},')
    out.append(f'            prizeSpots: {pts(lv["places"])}' + ("," if lv["scrolls"] else ""))
    if lv["scrolls"]:
        out.append(f'            scrolls: {pts(lv["scrolls"])}')
    out.append("        ),")
out.append("    ]")
out.append("}")
(here.parent / "NetHackSokoban" / "Levels.swift").write_text("\n".join(out) + "\n")
print("wrote Levels.swift", file=sys.stderr)
